---
spring:
  datasource:
    username: "${DB_USER:postgres}"
    password: "${DB_PASSWORD:example}"
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}"
  flyway:
    baseline-on-migrate: true
    locations: "classpath:/db/migration"
  output:
    ansi:
      enabled: "ALWAYS"
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    properties:
      hibernate:
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: "validate"
    open-in-view: false
  servlet:
    multipart:
      max-file-size: "2MB"
      max-request-size: "2MB"
  data:
    redis:
      host: "${REDIS_HOST:0.0.0.0}"
      password: "${REDIS_PASSWORD:}"
      port: "${REDIS_PORT:6379}"
      repositories:
        enabled: true
  thymeleaf:
    cache: "${PRODUCTION:false}"
    enabled: true
    encoding: "UTF-8"
  session:
    store-type: "redis"
    timeout: "${SESSION_TIMEOUT:43200}"
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: "${SERVER_PORT:8081}"
  error:
    whitelabel:
      enabled: false
    path: "/error"
  http2:
    enabled: true
  forward-headers-strategy: "native"
logging:
  level:
    root: "${ROOT_DEBUG_LEVEL:INFO}"
application:
  base-uri: "${BASE_URI:http://gamma:8081}"
  production: "${PRODUCTION:false}"
  files:
    path: "${UPLOAD_FOLDER:./uploads/}"
  cookie:
    domain: "${COOKIE_DOMAIN:gamma}"
    path: "${COOKIE_PATH:/}"
    validity-time: 2628000
  mocking: "${IS_MOCKING:false}"
  admin-setup: "${ADMIN_SETUP:true}"
  gotify:
    key: "${GOTIFY_KEY:123abc}"
    url: "${GOTIFY_BASE_URL:http://localhost:8080}"
